/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline-variant": "var(--outline-variant)",
        "inverse-primary": "var(--inverse-primary)",
        "outline": "var(--outline)",
        "surface-container-highest": "var(--surface-container-highest)",
        "surface-variant": "var(--surface-variant)",
        "inverse-surface": "var(--inverse-surface)",
        "on-primary-fixed-variant": "var(--on-primary-fixed-variant)",
        "primary-container": "var(--primary-container)",
        primary: "var(--primary)",
        "surface-tint": "var(--surface-tint)",
        "primary-fixed-dim": "var(--primary-fixed-dim)",
        "surface-container": "var(--surface-container)",
        "surface-dim": "var(--surface-dim)",
        "tertiary-fixed": "var(--tertiary-fixed)",
        "on-error-container": "var(--on-error-container)",
        "surface-container-high": "var(--surface-container-high)",
        "surface-container-lowest": "var(--surface-container-lowest)",
        "on-tertiary": "var(--on-tertiary)",
        "on-surface-variant": "var(--on-surface-variant)",
        "on-secondary-fixed": "var(--on-secondary-fixed)",
        "surface-bright": "var(--surface-bright)",
        "on-secondary-fixed-variant": "var(--on-secondary-fixed-variant)",
        "inverse-on-surface": "var(--inverse-on-surface)",
        "primary-fixed": "var(--primary-fixed)",
        "on-secondary-container": "var(--on-secondary-container)",
        "on-secondary": "var(--on-secondary)",
        "on-tertiary-fixed-variant": "var(--on-tertiary-fixed-variant)",
        background: "var(--background)",
        surface: "var(--surface)",
        "on-primary-fixed": "var(--on-primary-fixed)",
        "on-primary-container": "var(--on-primary-container)",
        "secondary-container": "var(--secondary-container)",
        "error-container": "var(--error-container)",
        "on-tertiary-container": "var(--on-tertiary-container)",
        "tertiary-fixed-dim": "var(--tertiary-fixed-dim)",
        "on-tertiary-fixed": "var(--on-tertiary-fixed)",
        "on-background": "var(--on-background)",
        "surface-container-low": "var(--surface-container-low)",
        tertiary: "var(--tertiary)",
        secondary: "var(--secondary)",
        "secondary-fixed": "var(--secondary-fixed)",
        "on-primary": "var(--on-primary)",
        "on-surface": "var(--on-surface)",
        error: "var(--error)",
        "on-error": "var(--on-error)",
        "secondary-fixed-dim": "var(--secondary-fixed-dim)",
        "tertiary-container": "var(--tertiary-container)",
        "low-queue": "#22C55E",
        "medium-queue": "#F59E0B",
        "high-queue": "#EF4444",
        "critical-queue": "#B91C1C",
      },
      borderRadius: {
        DEFAULT: "var(--radius-default)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        full: "9999px",
      },
      spacing: {
        sm: "8px",
        xs: "4px",
        gutter: "24px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        base: "4px",
        "container-max": "1280px",
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Granetha", "Bebas Neue", "Anton", "sans-serif"],
        "mono-data": ["Inter", "monospace"],
        "display-lg": ["Granetha", "Bebas Neue", "Anton", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-md": ["Granetha", "Bebas Neue", "Anton", "sans-serif"],
        "label-sm": ["Moonscape", "Bodoni Moda", "Playfair Display", "serif"],
        "label-md": ["Moonscape", "Bodoni Moda", "Playfair Display", "serif"],
        "headline-sm": ["Granetha", "Bebas Neue", "Anton", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "mono-data": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "14px", letterSpacing: "0.05em", fontWeight: "500" }],
        "label-md": ["14px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
      boxShadow: {
        "ambient-soft": "0 1px 3px rgba(15, 23, 42, 0.05), 0 1px 2px rgba(15, 23, 42, 0.02)",
        "elevation-1": "0 1px 3px rgba(15, 23, 42, 0.05), 0 1px 2px rgba(15, 23, 42, 0.02)",
        "elevation-2": "0 10px 15px -3px rgba(15, 23, 42, 0.08)",
      },
    },
  },
  plugins: [],
}
